# Site settings
title: Bir Bilgisayar Çaylağının Günlüğü
tagline: 
email: ztugcesirin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Merhaba, benim adım Tuğçe. Yeni mezun bir bilgisayar mühendisiyim.
  Bir yıldır Salesforce platformunda yazılım geliştiriyorum.
baseurl: "/gaya" # the subpath of your site, e.g. /blog/
url: "http://http://gayan.me" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Tuğçe Şirin"
author_thumbnail: "/assets/images/tugce.jpeg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: ztugcesirin
    twitter: ztugcesirin
    facebook: ztugcesirin
    gplus: +ztugcesirin
    # dribble: gayanvirajith
    pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
